{% set version = "0.10.3" %}

package:
  name: gooseepm-split
  version: {{ version }}

source:
  url: https://github.com/tdegeus/GooseEPM/archive/v{{ version }}.tar.gz
  sha256: 70c7934e749ec12c0edbcd698db43dd5ca5904109947cfb79be51c389f0ea6b8

build:
  number: 0

outputs:

  - name: gooseepm

    script: install.sh  # [unix]
    script: install.bat  # [win]

    build:
      script_env: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}

    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake
        - make  # [unix]
      host:
        - prrng >=1.8.0
        - xtensor >=0.24.4
      run:
        - prrng >=1.8.0
        - xtensor >=0.24.4

    test:
      commands:
        - test -d ${PREFIX}/include/GooseEPM  # [unix]
        - test -f ${PREFIX}/include/GooseEPM/System.h  # [unix]
        - test -f ${PREFIX}/lib/cmake/GooseEPM/GooseEPMConfig.cmake  # [unix]
        - if not exist %LIBRARY_PREFIX%\include\GooseEPM\System.h exit 1  # [win]
        - if not exist %LIBRARY_PREFIX%\lib\cmake\GooseEPM\GooseEPMConfig.cmake exit 1  # [win]

  - name: python-gooseepm

    script: install_python.sh  # [unix]
    script: install_python.bat  # [win]

    build:
      script_env: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
      skip: true  # [python_impl == 'pypy']

    requirements:
      build:
        - python                              # [build_platform != target_platform]
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
        - numpy *                             # [build_platform != target_platform]
        - setuptools_scm                      # [build_platform != target_platform]
        - {{ compiler('cxx') }}
        - cmake
        - make  # [unix]
        - ninja
      host:
        - numpy *
        - pip
        - prrng >=1.8.0
        - pybind11
        - pybind11-abi
        - python
        - scikit-build
        - setuptools_scm
        - xtensor >=0.24.4
        - xtensor-python
      run:
        - numpy *
        - python
        - scipy

    test:
      imports:
        - GooseEPM
      commands:
        - pip check
        - python -c "import GooseEPM; assert GooseEPM.version() == '{{ version }}'"
      requires:
        - pip

about:
  home: https://github.com/tdegeus/GooseEPM
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Elasto-plastic model.
  description: Elasto-plastic model.
  doc_url: https://tdegeus.github.io/GooseEPM
  dev_url: https://github.com/tdegeus/GooseEPM

extra:
  recipe-maintainers:
    - tdegeus
